services:
  db:
    image: postgres:15
    container_name: boilerplate_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: boilerplate_api
    restart: always
    ports:
      - '${SERVER_PORT:-3001}:3001'
    env_file:
      - .env
      - ./server/.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/generated

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: boilerplate_client
    restart: always
    ports:
      - '${CLIENT_PORT:-5173}:5173'
    volumes:
      - ./client:/app
      - /app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    container_name: boilerplate_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data:
